# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51b1eceb87ae2e91c2fb6a442d7dd2fd55d119a5658379f059135f2e8034f3b4858e378f3dc5b8409b445515a4488b8336b54562638845fa2a3558678236b859

test:
  secret_key_base: ba4b79e8fa2d4d8dcb7c791de81461bbd1f6e11a8623c0cda5593ea3ed6cae1b7ce097d5b37198c8c367d34c5de1c3c50ce8eee72a3137e9fe761cc231de1d73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
